version: '3.7'

services:

   db:
     image: mysql:5.7
     volumes:
       - ./db_data:/var/lib/mysql:delegated
     restart: "no"
     ports:
       - "33049:3306"
     environment:
       MYSQL_ROOT_PASSWORD: nourishing_life_root
       MYSQL_DATABASE: nourishing_life_db
       MYSQL_USER: nourishing_life_user
       MYSQL_PASSWORD: nourishing_life_psw

   wordpress:
     depends_on:
       - db
     image: wordpress:latest
     volumes:
       - ./../NourishingLife/:/var/www/html:delegated
       - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini:delegated
     ports:
       - "8049:80"
     restart: "no"
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: nourishing_life_user
       WORDPRESS_DB_PASSWORD: nourishing_life_psw
       WORDPRESS_DB_NAME: nourishing_life_db

volumes:
    db_data: 
    uploads.ini: 
